/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../../base';
// @ts-ignore
import type { UsageSpaceStatItemArrayWrapper } from '../../models';
/**
 * SettingsStatisticsApi - axios parameter creator
 * @export
 */
export const SettingsStatisticsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns the space usage statistics for the module with the ID specified in the request.
         * @summary Get the space usage statistics
         * @param {string} id The ID extracted from the route parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSpaceUsageStatistics: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSpaceUsageStatistics', 'id', id)
            const localVarPath = `/api/2.0/settings/statistics/spaceusage/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Basic required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", ["read", "write"], configuration)

            // authentication ApiKeyBearer required
            await setApiKeyToObject(localVarHeaderParameter, "ApiKeyBearer", configuration)

            // authentication asc_auth_key required

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication OpenId required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SettingsStatisticsApi - functional programming interface
 * @export
 */
export const SettingsStatisticsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SettingsStatisticsApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns the space usage statistics for the module with the ID specified in the request.
         * @summary Get the space usage statistics
         * @param {string} id The ID extracted from the route parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSpaceUsageStatistics(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsageSpaceStatItemArrayWrapper>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSpaceUsageStatistics(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SettingsStatisticsApi.getSpaceUsageStatistics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SettingsStatisticsApi - factory interface
 * @export
 */
export const SettingsStatisticsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SettingsStatisticsApiFp(configuration)
    return {
        /**
         * Returns the space usage statistics for the module with the ID specified in the request.
         * @summary Get the space usage statistics
         * @param {string} id The ID extracted from the route parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSpaceUsageStatistics(id: string, options?: RawAxiosRequestConfig): AxiosPromise<UsageSpaceStatItemArrayWrapper> {
            return localVarFp.getSpaceUsageStatistics(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SettingsStatisticsApi - object-oriented interface
 * @export
 * @class SettingsStatisticsApi
 * @extends {BaseAPI}
 */
export class SettingsStatisticsApi extends BaseAPI {
    /**
     * Returns the space usage statistics for the module with the ID specified in the request.
     * @summary Get the space usage statistics
     * @param {string} id The ID extracted from the route parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SettingsStatisticsApi
     */
    public getSpaceUsageStatistics(id: string, options?: RawAxiosRequestConfig) {
        return SettingsStatisticsApiFp(this.configuration).getSpaceUsageStatistics(id, options).then((request) => request(this.axios, this.basePath));
    }
}

