/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../../base';
// @ts-ignore
import type { EmployeeType } from '../../models';
// @ts-ignore
import type { Int64Wrapper } from '../../models';
// @ts-ignore
import type { StringWrapper } from '../../models';
// @ts-ignore
import type { UserInfoWrapper } from '../../models';
/**
 * PortalUsersApi - axios parameter creator
 * @export
 */
export const PortalUsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns an invitation link for joining the portal.
         * @summary Get an invitation link
         * @param {EmployeeType} employeeType The type of employee role for the invitation link (All, RoomAdmin, Guest, DocSpaceAdmin, User).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        geInviteLink: async (employeeType: EmployeeType, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'employeeType' is not null or undefined
            assertParamExists('geInviteLink', 'employeeType', employeeType)
            const localVarPath = `/api/2.0/portal/users/invite/{employeeType}`
                .replace(`{${"employeeType"}}`, encodeURIComponent(String(employeeType)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Basic required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", ["read", "write"], configuration)

            // authentication ApiKeyBearer required
            await setApiKeyToObject(localVarHeaderParameter, "ApiKeyBearer", configuration)

            // authentication asc_auth_key required

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication OpenId required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a user with the ID specified in the request from the current portal.
         * @summary Get a user by ID
         * @param {string} userID The user ID extracted from the route parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUser: async (userID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userID' is not null or undefined
            assertParamExists('getUser', 'userID', userID)
            const localVarPath = `/api/2.0/portal/users/{userID}`
                .replace(`{${"userID"}}`, encodeURIComponent(String(userID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Basic required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", ["read", "write"], configuration)

            // authentication ApiKeyBearer required
            await setApiKeyToObject(localVarHeaderParameter, "ApiKeyBearer", configuration)

            // authentication asc_auth_key required

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication OpenId required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a number of portal users.
         * @summary Get a number of portal users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsersCount: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/2.0/portal/userscount`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Basic required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", ["read", "write"], configuration)

            // authentication ApiKeyBearer required
            await setApiKeyToObject(localVarHeaderParameter, "ApiKeyBearer", configuration)

            // authentication asc_auth_key required

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication OpenId required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Marks a gift message as read.
         * @summary Mark a gift message as read
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markPresentAsReaded: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/2.0/portal/present/mark`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Basic required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", ["read", "write"], configuration)

            // authentication ApiKeyBearer required
            await setApiKeyToObject(localVarHeaderParameter, "ApiKeyBearer", configuration)

            // authentication asc_auth_key required

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication OpenId required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Sends congratulations to the user after registering a portal.
         * @summary Send congratulations
         * @param {string} [userid] The user ID to receive the congratulatory message.
         * @param {string} [key] The template identifier or email configuration key.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendCongratulations: async (userid?: string, key?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/2.0/portal/sendcongratulations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userid !== undefined) {
                localVarQueryParameter['Userid'] = userid;
            }

            if (key !== undefined) {
                localVarQueryParameter['Key'] = key;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PortalUsersApi - functional programming interface
 * @export
 */
export const PortalUsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PortalUsersApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns an invitation link for joining the portal.
         * @summary Get an invitation link
         * @param {EmployeeType} employeeType The type of employee role for the invitation link (All, RoomAdmin, Guest, DocSpaceAdmin, User).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async geInviteLink(employeeType: EmployeeType, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StringWrapper>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.geInviteLink(employeeType, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PortalUsersApi.geInviteLink']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a user with the ID specified in the request from the current portal.
         * @summary Get a user by ID
         * @param {string} userID The user ID extracted from the route parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUser(userID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserInfoWrapper>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUser(userID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PortalUsersApi.getUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a number of portal users.
         * @summary Get a number of portal users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUsersCount(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Int64Wrapper>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUsersCount(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PortalUsersApi.getUsersCount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Marks a gift message as read.
         * @summary Mark a gift message as read
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async markPresentAsReaded(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.markPresentAsReaded(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PortalUsersApi.markPresentAsReaded']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Sends congratulations to the user after registering a portal.
         * @summary Send congratulations
         * @param {string} [userid] The user ID to receive the congratulatory message.
         * @param {string} [key] The template identifier or email configuration key.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendCongratulations(userid?: string, key?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendCongratulations(userid, key, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PortalUsersApi.sendCongratulations']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PortalUsersApi - factory interface
 * @export
 */
export const PortalUsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PortalUsersApiFp(configuration)
    return {
        /**
         * Returns an invitation link for joining the portal.
         * @summary Get an invitation link
         * @param {EmployeeType} employeeType The type of employee role for the invitation link (All, RoomAdmin, Guest, DocSpaceAdmin, User).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        geInviteLink(employeeType: EmployeeType, options?: RawAxiosRequestConfig): AxiosPromise<StringWrapper> {
            return localVarFp.geInviteLink(employeeType, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a user with the ID specified in the request from the current portal.
         * @summary Get a user by ID
         * @param {string} userID The user ID extracted from the route parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUser(userID: string, options?: RawAxiosRequestConfig): AxiosPromise<UserInfoWrapper> {
            return localVarFp.getUser(userID, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a number of portal users.
         * @summary Get a number of portal users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsersCount(options?: RawAxiosRequestConfig): AxiosPromise<Int64Wrapper> {
            return localVarFp.getUsersCount(options).then((request) => request(axios, basePath));
        },
        /**
         * Marks a gift message as read.
         * @summary Mark a gift message as read
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markPresentAsReaded(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.markPresentAsReaded(options).then((request) => request(axios, basePath));
        },
        /**
         * Sends congratulations to the user after registering a portal.
         * @summary Send congratulations
         * @param {string} [userid] The user ID to receive the congratulatory message.
         * @param {string} [key] The template identifier or email configuration key.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendCongratulations(userid?: string, key?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.sendCongratulations(userid, key, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PortalUsersApi - object-oriented interface
 * @export
 * @class PortalUsersApi
 * @extends {BaseAPI}
 */
export class PortalUsersApi extends BaseAPI {
    /**
     * Returns an invitation link for joining the portal.
     * @summary Get an invitation link
     * @param {EmployeeType} employeeType The type of employee role for the invitation link (All, RoomAdmin, Guest, DocSpaceAdmin, User).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PortalUsersApi
     */
    public geInviteLink(employeeType: EmployeeType, options?: RawAxiosRequestConfig) {
        return PortalUsersApiFp(this.configuration).geInviteLink(employeeType, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a user with the ID specified in the request from the current portal.
     * @summary Get a user by ID
     * @param {string} userID The user ID extracted from the route parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PortalUsersApi
     */
    public getUser(userID: string, options?: RawAxiosRequestConfig) {
        return PortalUsersApiFp(this.configuration).getUser(userID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a number of portal users.
     * @summary Get a number of portal users
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PortalUsersApi
     */
    public getUsersCount(options?: RawAxiosRequestConfig) {
        return PortalUsersApiFp(this.configuration).getUsersCount(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Marks a gift message as read.
     * @summary Mark a gift message as read
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PortalUsersApi
     */
    public markPresentAsReaded(options?: RawAxiosRequestConfig) {
        return PortalUsersApiFp(this.configuration).markPresentAsReaded(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Sends congratulations to the user after registering a portal.
     * @summary Send congratulations
     * @param {string} [userid] The user ID to receive the congratulatory message.
     * @param {string} [key] The template identifier or email configuration key.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PortalUsersApi
     */
    public sendCongratulations(userid?: string, key?: string, options?: RawAxiosRequestConfig) {
        return PortalUsersApiFp(this.configuration).sendCongratulations(userid, key, options).then((request) => request(this.axios, this.basePath));
    }
}

