/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CspRequestsDto } from '../models';
// @ts-ignore
import type { CspWrapper } from '../models';
/**
 * SecurityCSPApi - axios parameter creator
 * @export
 */
export const SecurityCSPApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Configures the CSP (Content Security Policy) settings for the current portal.
         * @summary Configure CSP settings
         * @param {CspRequestsDto} [cspRequestsDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        csp: async (cspRequestsDto?: CspRequestsDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/2.0/security/csp`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Basic required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", ["read", "write"], configuration)

            // authentication ApiKeyBearer required
            await setApiKeyToObject(localVarHeaderParameter, "ApiKeyBearer", configuration)

            // authentication asc_auth_key required

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication OpenId required


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cspRequestsDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the CSP (Content Security Policy) settings for the current portal.
         * @summary Get CSP settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCsp: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/2.0/security/csp`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SecurityCSPApi - functional programming interface
 * @export
 */
export const SecurityCSPApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SecurityCSPApiAxiosParamCreator(configuration)
    return {
        /**
         * Configures the CSP (Content Security Policy) settings for the current portal.
         * @summary Configure CSP settings
         * @param {CspRequestsDto} [cspRequestsDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async csp(cspRequestsDto?: CspRequestsDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CspWrapper>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.csp(cspRequestsDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SecurityCSPApi.csp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the CSP (Content Security Policy) settings for the current portal.
         * @summary Get CSP settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCsp(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CspWrapper>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCsp(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SecurityCSPApi.getCsp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SecurityCSPApi - factory interface
 * @export
 */
export const SecurityCSPApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SecurityCSPApiFp(configuration)
    return {
        /**
         * Configures the CSP (Content Security Policy) settings for the current portal.
         * @summary Configure CSP settings
         * @param {CspRequestsDto} [cspRequestsDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        csp(cspRequestsDto?: CspRequestsDto, options?: RawAxiosRequestConfig): AxiosPromise<CspWrapper> {
            return localVarFp.csp(cspRequestsDto, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the CSP (Content Security Policy) settings for the current portal.
         * @summary Get CSP settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCsp(options?: RawAxiosRequestConfig): AxiosPromise<CspWrapper> {
            return localVarFp.getCsp(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SecurityCSPApi - object-oriented interface
 * @export
 * @class SecurityCSPApi
 * @extends {BaseAPI}
 */
export class SecurityCSPApi extends BaseAPI {
    /**
     * Configures the CSP (Content Security Policy) settings for the current portal.
     * @summary Configure CSP settings
     * @param {CspRequestsDto} [cspRequestsDto] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SecurityCSPApi
     */
    public csp(cspRequestsDto?: CspRequestsDto, options?: RawAxiosRequestConfig) {
        return SecurityCSPApiFp(this.configuration).csp(cspRequestsDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the CSP (Content Security Policy) settings for the current portal.
     * @summary Get CSP settings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SecurityCSPApi
     */
    public getCsp(options?: RawAxiosRequestConfig) {
        return SecurityCSPApiFp(this.configuration).getCsp(options).then((request) => request(this.axios, this.basePath));
    }
}

