/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * [0 - SSO, 1 - LDAP, 2 - Standart]
 * @export
 * @enum {number}
 */

export const AccountLoginType = {
    /**
    * SSO
    */
    SSO: 0,
    /**
    * LDAP
    */
    LDAP: 1,
    /**
    * Standart
    */
    Standart: 2
} as const;

export type AccountLoginType = typeof AccountLoginType[keyof typeof AccountLoginType];



