/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * [0 - None, 1 - Create, 2 - Update, 3 - Delete, 4 - Link, 5 - Unlink, 6 - Attach, 7 - Detach, 8 - Send, 9 - Import, 10 - Export, 11 - Update access, 12 - Download, 13 - Upload, 14 - Copy, 15 - Move, 16 - Reassigns, 17 - Follow, 18 - Unfollow, 19 - Logout]
 * @export
 * @enum {number}
 */

export const ActionType = {
    /**
    * None
    */
    None: 0,
    /**
    * Create
    */
    Create: 1,
    /**
    * Update
    */
    Update: 2,
    /**
    * Delete
    */
    Delete: 3,
    /**
    * Link
    */
    Link: 4,
    /**
    * Unlink
    */
    Unlink: 5,
    /**
    * Attach
    */
    Attach: 6,
    /**
    * Detach
    */
    Detach: 7,
    /**
    * Send
    */
    Send: 8,
    /**
    * Import
    */
    Import: 9,
    /**
    * Export
    */
    Export: 10,
    /**
    * Update access
    */
    UpdateAccess: 11,
    /**
    * Download
    */
    Download: 12,
    /**
    * Upload
    */
    Upload: 13,
    /**
    * Copy
    */
    Copy: 14,
    /**
    * Move
    */
    Move: 15,
    /**
    * Reassigns
    */
    Reassigns: 16,
    /**
    * Follow
    */
    Follow: 17,
    /**
    * Unfollow
    */
    Unfollow: 18,
    /**
    * Logout
    */
    Logout: 19
} as const;

export type ActionType = typeof ActionType[keyof typeof ActionType];



