/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ActionConfig } from './action-config';

/**
 * The config parameter which contains the information about the action in the document that will be scrolled to.
 * @export
 * @interface ActionLinkConfig
 */
export interface ActionLinkConfig {
    /**
     * 
     * @type {ActionConfig}
     * @memberof ActionLinkConfig
     */
    'action'?: ActionConfig;
}

