/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ActiveConnectionsWrapperLinksInner
 */
export interface ActiveConnectionsWrapperLinksInner {
    /**
     * 
     * @type {string}
     * @memberof ActiveConnectionsWrapperLinksInner
     */
    'href'?: string;
    /**
     * 
     * @type {string}
     * @memberof ActiveConnectionsWrapperLinksInner
     */
    'action'?: string;
}

