/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The parameters for archiving a room.
 * @export
 * @interface ArchiveRoomRequest
 */
export interface ArchiveRoomRequest {
    /**
     * Specifies whether to archive a room after the editing session is finished or not.
     * @type {boolean}
     * @memberof ArchiveRoomRequest
     */
    'deleteAfter'?: boolean;
}

