/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DateToAutoCleanUp } from './date-to-auto-clean-up';

/**
 * The auto-clearing request parameters.
 * @export
 * @interface AutoCleanupRequestDto
 */
export interface AutoCleanupRequestDto {
    /**
     * Specifies whether to enable the auto-clearing or not.
     * @type {boolean}
     * @memberof AutoCleanupRequestDto
     */
    'set'?: boolean;
    /**
     * 
     * @type {DateToAutoCleanUp}
     * @memberof AutoCleanupRequestDto
     */
    'gap'?: DateToAutoCleanUp;
}



