/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BackupStorageType } from './backup-storage-type';
// May contain unused imports in some cases
// @ts-ignore
import type { ItemKeyValuePairObjectObject } from './item-key-value-pair-object-object';

/**
 * The backup restoring parameters.
 * @export
 * @interface BackupRestoreDto
 */
export interface BackupRestoreDto {
    /**
     * The backup ID.
     * @type {string}
     * @memberof BackupRestoreDto
     */
    'backupId'?: string | null;
    /**
     * 
     * @type {BackupStorageType}
     * @memberof BackupRestoreDto
     */
    'storageType'?: BackupStorageType;
    /**
     * The backup storage parameters.
     * @type {Array<ItemKeyValuePairObjectObject>}
     * @memberof BackupRestoreDto
     */
    'storageParams'?: Array<ItemKeyValuePairObjectObject> | null;
    /**
     * Notifies users about the portal restoring process or not.
     * @type {boolean}
     * @memberof BackupRestoreDto
     */
    'notify'?: boolean;
    /**
     * Specifies if a dump will be created or not.
     * @type {boolean}
     * @memberof BackupRestoreDto
     */
    'dump'?: boolean;
}



