/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The request parameters for changing the client activation status.
 * @export
 * @interface ChangeClientActivationRequest
 */
export interface ChangeClientActivationRequest {
    /**
     * The client activation status.
     * @type {boolean}
     * @memberof ChangeClientActivationRequest
     */
    'status': boolean;
}

