/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CheckDestFolderResult } from './check-dest-folder-result';
// May contain unused imports in some cases
// @ts-ignore
import type { FileEntryDto } from './file-entry-dto';

/**
 * The destination folder checking information.
 * @export
 * @interface CheckDestFolderDto
 */
export interface CheckDestFolderDto {
    /**
     * 
     * @type {CheckDestFolderResult}
     * @memberof CheckDestFolderDto
     */
    'result'?: CheckDestFolderResult;
    /**
     * The list of files of the destination folder.
     * @type {Array<FileEntryDto>}
     * @memberof CheckDestFolderDto
     */
    'files'?: Array<FileEntryDto> | null;
}



