/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ClientResponse
 */
export interface ClientResponse {
    /**
     * 
     * @type {string}
     * @memberof ClientResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientResponse
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof ClientResponse
     */
    'tenant'?: number;
    /**
     * 
     * @type {Set<string>}
     * @memberof ClientResponse
     */
    'scopes'?: Set<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ClientResponse
     */
    'enabled'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ClientResponse
     */
    'client_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientResponse
     */
    'client_secret'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientResponse
     */
    'website_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientResponse
     */
    'terms_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientResponse
     */
    'policy_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientResponse
     */
    'logo'?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof ClientResponse
     */
    'authentication_methods'?: Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof ClientResponse
     */
    'redirect_uris'?: Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof ClientResponse
     */
    'allowed_origins'?: Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof ClientResponse
     */
    'logout_redirect_uris'?: Set<string>;
    /**
     * 
     * @type {string}
     * @memberof ClientResponse
     */
    'created_on'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientResponse
     */
    'created_by'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientResponse
     */
    'modified_on'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientResponse
     */
    'modified_by'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ClientResponse
     */
    'is_public'?: boolean;
}

