/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CoEditingConfigMode } from './co-editing-config-mode';

/**
 * The co-editing configuration parameters.
 * @export
 * @interface CoEditingConfig
 */
export interface CoEditingConfig {
    /**
     * Specifies if the co-editing mode can be changed in the editor interface or not.
     * @type {boolean}
     * @memberof CoEditingConfig
     */
    'change'?: boolean;
    /**
     * Specifies if the co-editing mode is fast.
     * @type {boolean}
     * @memberof CoEditingConfig
     */
    'fast'?: boolean;
    /**
     * 
     * @type {CoEditingConfigMode}
     * @memberof CoEditingConfig
     */
    'mode'?: CoEditingConfigMode;
}



