/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CopyAsJsonElementDestFolderId } from './copy-as-json-element-dest-folder-id';

/**
 * The parameters for copying a file.
 * @export
 * @interface CopyAsJsonElement
 */
export interface CopyAsJsonElement {
    /**
     * The copied file name.
     * @type {string}
     * @memberof CopyAsJsonElement
     */
    'destTitle': string | null;
    /**
     * 
     * @type {CopyAsJsonElementDestFolderId}
     * @memberof CopyAsJsonElement
     */
    'destFolderId': CopyAsJsonElementDestFolderId;
    /**
     * Specifies whether to allow creating the copied file of an external extension or not.
     * @type {boolean}
     * @memberof CopyAsJsonElement
     */
    'enableExternalExt'?: boolean;
    /**
     * The copied file password.
     * @type {string}
     * @memberof CopyAsJsonElement
     */
    'password'?: string | null;
    /**
     * Specifies whether to convert the file to form or not.
     * @type {boolean}
     * @memberof CopyAsJsonElement
     */
    'toForm'?: boolean;
}

