/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The parameters for creating a folder.
 * @export
 * @interface CreateFolder
 */
export interface CreateFolder {
    /**
     * The folder title to create.
     * @type {string}
     * @memberof CreateFolder
     */
    'title': string | null;
}

