/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The request parameters for creating a new API key.
 * @export
 * @interface CreateApiKeyRequestDto
 */
export interface CreateApiKeyRequestDto {
    /**
     * The API key name.
     * @type {string}
     * @memberof CreateApiKeyRequestDto
     */
    'name': string;
    /**
     * The list of permissions granted to the API key.
     * @type {Array<string>}
     * @memberof CreateApiKeyRequestDto
     */
    'permissions'?: Array<string> | null;
    /**
     * The number of days until the API key expires (null for no expiration).
     * @type {number}
     * @memberof CreateApiKeyRequestDto
     */
    'expiresInDays'?: number | null;
}

