/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The parameters for setting the Custom Filter editing mode.
 * @export
 * @interface CustomFilterParameters
 */
export interface CustomFilterParameters {
    /**
     * Specifies whether the Custom Filter editing mode is enabled or not.
     * @type {boolean}
     * @memberof CustomFilterParameters
     */
    'enabled'?: boolean;
}

