/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DarkThemeSettingsType } from './dark-theme-settings-type';

/**
 * The theme settings request parameters.
 * @export
 * @interface DarkThemeSettingsRequestDto
 */
export interface DarkThemeSettingsRequestDto {
    /**
     * 
     * @type {DarkThemeSettingsType}
     * @memberof DarkThemeSettingsRequestDto
     */
    'theme'?: DarkThemeSettingsType;
}



