/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The parameters for deleting a file.
 * @export
 * @interface Delete
 */
export interface Delete {
    /**
     * Specifies whether to delete a file after the editing session is finished or not.
     * @type {boolean}
     * @memberof Delete
     */
    'deleteAfter'?: boolean;
    /**
     * Specifies whether to move a file to the \\\"Trash\\\" folder or delete it immediately.
     * @type {boolean}
     * @memberof Delete
     */
    'immediately'?: boolean;
}

