/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The request parameters for managing the DNS (Domain Name System) settings.
 * @export
 * @interface DnsSettingsRequestsDto
 */
export interface DnsSettingsRequestsDto {
    /**
     * The DNS (Domain Name System) configuration name.
     * @type {string}
     * @memberof DnsSettingsRequestsDto
     */
    'dnsName'?: string | null;
    /**
     * Specifies whether the DNS settings are enabled.
     * @type {boolean}
     * @memberof DnsSettingsRequestsDto
     */
    'enable'?: boolean;
}

