/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FileReferenceData } from './file-reference-data';
// May contain unused imports in some cases
// @ts-ignore
import type { InfoConfigDto } from './info-config-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { Options } from './options';
// May contain unused imports in some cases
// @ts-ignore
import type { PermissionsConfig } from './permissions-config';

/**
 * The document config parameters.
 * @export
 * @interface DocumentConfigDto
 */
export interface DocumentConfigDto {
    /**
     * The file type of the document.
     * @type {string}
     * @memberof DocumentConfigDto
     */
    'fileType'?: string | null;
    /**
     * 
     * @type {InfoConfigDto}
     * @memberof DocumentConfigDto
     */
    'info'?: InfoConfigDto;
    /**
     * Specifies if the documnet is linked for current user.
     * @type {boolean}
     * @memberof DocumentConfigDto
     */
    'isLinkedForMe'?: boolean;
    /**
     * The document key.
     * @type {string}
     * @memberof DocumentConfigDto
     */
    'key'?: string | null;
    /**
     * 
     * @type {PermissionsConfig}
     * @memberof DocumentConfigDto
     */
    'permissions'?: PermissionsConfig;
    /**
     * The shared link parameter of the document.
     * @type {string}
     * @memberof DocumentConfigDto
     */
    'sharedLinkParam'?: string | null;
    /**
     * The shared link key of the document.
     * @type {string}
     * @memberof DocumentConfigDto
     */
    'sharedLinkKey'?: string | null;
    /**
     * 
     * @type {FileReferenceData}
     * @memberof DocumentConfigDto
     */
    'referenceData'?: FileReferenceData;
    /**
     * The document title.
     * @type {string}
     * @memberof DocumentConfigDto
     */
    'title'?: string | null;
    /**
     * The document url.
     * @type {string}
     * @memberof DocumentConfigDto
     */
    'url'?: string | null;
    /**
     * Indicates whether this is a form.
     * @type {boolean}
     * @memberof DocumentConfigDto
     */
    'isForm'?: boolean;
    /**
     * 
     * @type {Options}
     * @memberof DocumentConfigDto
     */
    'options'?: Options;
}

