/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DistributedTaskStatus } from './distributed-task-status';

/**
 * The document builder task parameters.
 * @export
 * @interface DocumentBuilderTaskDto
 */
export interface DocumentBuilderTaskDto {
    /**
     * The document builder ID.
     * @type {string}
     * @memberof DocumentBuilderTaskDto
     */
    'id'?: string | null;
    /**
     * The error message occured while the document building process.
     * @type {string}
     * @memberof DocumentBuilderTaskDto
     */
    'error'?: string | null;
    /**
     * The percentage of the progress of the document building process.
     * @type {number}
     * @memberof DocumentBuilderTaskDto
     */
    'percentage'?: number;
    /**
     * Specifies whether the document building process is completed or not.
     * @type {boolean}
     * @memberof DocumentBuilderTaskDto
     */
    'isCompleted'?: boolean;
    /**
     * 
     * @type {DistributedTaskStatus}
     * @memberof DocumentBuilderTaskDto
     */
    'status'?: DistributedTaskStatus;
    /**
     * The result file ID.
     * @type {any}
     * @memberof DocumentBuilderTaskDto
     */
    'resultFileId'?: any | null;
    /**
     * The result file name.
     * @type {string}
     * @memberof DocumentBuilderTaskDto
     */
    'resultFileName'?: string | null;
    /**
     * The result file URL.
     * @type {string}
     * @memberof DocumentBuilderTaskDto
     */
    'resultFileUrl'?: string | null;
}



