/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The information about the file editing history author.
 * @export
 * @interface EditHistoryAuthor
 */
export interface EditHistoryAuthor {
    /**
     * The author ID.
     * @type {string}
     * @memberof EditHistoryAuthor
     */
    'id'?: string | null;
    /**
     * The author name.
     * @type {string}
     * @memberof EditHistoryAuthor
     */
    'name'?: string | null;
}

