/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EditHistoryUrl } from './edit-history-url';

/**
 * The file editing history data.
 * @export
 * @interface EditHistoryDataDto
 */
export interface EditHistoryDataDto {
    /**
     * The URL address of the file with the document changes data.
     * @type {string}
     * @memberof EditHistoryDataDto
     */
    'changesUrl'?: string | null;
    /**
     * The document identifier used to unambiguously identify the document file.
     * @type {string}
     * @memberof EditHistoryDataDto
     */
    'key'?: string | null;
    /**
     * 
     * @type {EditHistoryUrl}
     * @memberof EditHistoryDataDto
     */
    'previous'?: EditHistoryUrl;
    /**
     * The encrypted signature added to the parameter in the form of a token.
     * @type {string}
     * @memberof EditHistoryDataDto
     */
    'token'?: string | null;
    /**
     * The URL address of the current document version.
     * @type {string}
     * @memberof EditHistoryDataDto
     */
    'url'?: string | null;
    /**
     * The document version number.
     * @type {number}
     * @memberof EditHistoryDataDto
     */
    'version'?: number;
    /**
     * The document extension.
     * @type {string}
     * @memberof EditHistoryDataDto
     */
    'fileType'?: string | null;
}

