/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * [0 - All, 1 - Room admin, 2 - Guest, 3 - DocSpace admin, 4 - User]
 * @export
 * @enum {number}
 */

export const EmployeeType = {
    /**
    * All
    */
    All: 0,
    /**
    * Room admin
    */
    RoomAdmin: 1,
    /**
    * Guest
    */
    Guest: 2,
    /**
    * DocSpace admin
    */
    DocSpaceAdmin: 3,
    /**
    * User
    */
    User: 4
} as const;

export type EmployeeType = typeof EmployeeType[keyof typeof EmployeeType];



