/**
 *
 * (c) Copyright Ascensio System SIA 2025
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */


/**
 * [0 - Not activated, 1 - Activated, 2 - Pending, 4 - Auto generated]
 * @export
 * @enum {number}
 */

export const EmployeeActivationStatus = {
    /**
    * Not activated
    */
    NotActivated: 0,
    /**
    * Activated
    */
    Activated: 1,
    /**
    * Pending
    */
    Pending: 2,
    /**
    * Auto generated
    */
    AutoGenerated: 4
} as const;

export type EmployeeActivationStatus = typeof EmployeeActivationStatus[keyof typeof EmployeeActivationStatus];



