/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The encryption keys of the editor configuration.
 * @export
 * @interface EncryptionKeysConfig
 */
export interface EncryptionKeysConfig {
    /**
     * The crypto engine ID of the encryption key.
     * @type {string}
     * @memberof EncryptionKeysConfig
     */
    'cryptoEngineId'?: string | null;
    /**
     * The private key.
     * @type {string}
     * @memberof EncryptionKeysConfig
     */
    'privateKeyEnc'?: string | null;
    /**
     * The public key.
     * @type {string}
     * @memberof EncryptionKeysConfig
     */
    'publicKey'?: string | null;
}

