/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {number}
 */

export const EntryType = {
    /**
    * None
    */
    None: 0,
    /**
    * File
    */
    File: 1,
    /**
    * Folder
    */
    Folder: 2,
    /**
    * User
    */
    User: 23,
    /**
    * Group
    */
    Group: 24,
    /**
    * Room
    */
    Room: 25,
    /**
    * Tag
    */
    Tag: 26
} as const;

export type EntryType = typeof EntryType[keyof typeof EntryType];



