/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The external data parameters.
 * @export
 * @interface ExternalShareRequestParam
 */
export interface ExternalShareRequestParam {
    /**
     * The password to share external data.
     * @type {string}
     * @memberof ExternalShareRequestParam
     */
    'password'?: string | null;
}

