/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * [0 - None, 1 - Read and write, 2 - Read, 3 - Restrict, 4 - Varies, 5 - Review, 6 - Comment, 7 - Fill forms, 8 - Custom filter, 9 - Room manager, 10 - Editing, 11 - Content creator]
 * @export
 * @enum {number}
 */

export const FileShare = {
    /**
    * None
    */
    None: 0,
    /**
    * Read and write
    */
    ReadWrite: 1,
    /**
    * Read
    */
    Read: 2,
    /**
    * Restrict
    */
    Restrict: 3,
    /**
    * Varies
    */
    Varies: 4,
    /**
    * Review
    */
    Review: 5,
    /**
    * Comment
    */
    Comment: 6,
    /**
    * Fill forms
    */
    FillForms: 7,
    /**
    * Custom filter
    */
    CustomFilter: 8,
    /**
    * Room manager
    */
    RoomManager: 9,
    /**
    * Editing
    */
    Editing: 10,
    /**
    * Content creator
    */
    ContentCreator: 11
} as const;

export type FileShare = typeof FileShare[keyof typeof FileShare];



