/**
 *
 * (c) Copyright Ascensio System SIA 2025
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */


/**
 * An object that is generated by the integrator to uniquely identify a file in its system.
 * @export
 * @interface FileReferenceData
 */
export interface FileReferenceData {
    /**
     * The unique document identifier used by the service to get a link to the file.
     * @type {string}
     * @memberof FileReferenceData
     */
    'fileKey'?: string | null;
    /**
     * The unique system identifier.
     * @type {string}
     * @memberof FileReferenceData
     */
    'instanceId'?: string | null;
    /**
     * Room ID
     * @type {string}
     * @memberof FileReferenceData
     */
    'roomId'?: string | null;
    /**
     * Specifies if the room can be edited out or not.
     * @type {boolean}
     * @memberof FileReferenceData
     */
    'canEditRoom'?: boolean;
}

