/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiDateTime } from './api-date-time';
// May contain unused imports in some cases
// @ts-ignore
import type { FileShare } from './file-share';

/**
 * The external link request parameters.
 * @export
 * @interface FileLinkRequest
 */
export interface FileLinkRequest {
    /**
     * The external link ID.
     * @type {string}
     * @memberof FileLinkRequest
     */
    'linkId'?: string;
    /**
     * 
     * @type {FileShare}
     * @memberof FileLinkRequest
     */
    'access'?: FileShare;
    /**
     * 
     * @type {ApiDateTime}
     * @memberof FileLinkRequest
     */
    'expirationDate'?: ApiDateTime;
    /**
     * The link scope, whether it is internal or not.
     * @type {boolean}
     * @memberof FileLinkRequest
     */
    'internal'?: boolean;
    /**
     * Specifies whether the file link is primary or not.
     * @type {boolean}
     * @memberof FileLinkRequest
     */
    'primary'?: boolean;
}



