/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The Firebase parameters.
 * @export
 * @interface FirebaseDto
 */
export interface FirebaseDto {
    /**
     * The Firebase API key.
     * @type {string}
     * @memberof FirebaseDto
     */
    'apiKey'?: string | null;
    /**
     * The Firebase authentication domain.
     * @type {string}
     * @memberof FirebaseDto
     */
    'authDomain'?: string | null;
    /**
     * The Firebase project ID.
     * @type {string}
     * @memberof FirebaseDto
     */
    'projectId'?: string | null;
    /**
     * The Firebase storage bucket.
     * @type {string}
     * @memberof FirebaseDto
     */
    'storageBucket'?: string | null;
    /**
     * The Firebase messaging sender ID.
     * @type {string}
     * @memberof FirebaseDto
     */
    'messagingSenderId'?: string | null;
    /**
     * The Firebase application ID.
     * @type {string}
     * @memberof FirebaseDto
     */
    'appId'?: string | null;
    /**
     * The Firebase measurement ID.
     * @type {string}
     * @memberof FirebaseDto
     */
    'measurementId'?: string | null;
    /**
     * The Firebase database URL.
     * @type {string}
     * @memberof FirebaseDto
     */
    'databaseURL'?: string | null;
}

