/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * [0 - Stop, 1 - Resume]
 * @export
 * @enum {number}
 */

export const FormFillingManageAction = {
    /**
    * Stop
    */
    Stop: 0,
    /**
    * Resume
    */
    Resume: 1
} as const;

export type FormFillingManageAction = typeof FormFillingManageAction[keyof typeof FormFillingManageAction];



