/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ActiveConnectionsWrapperLinksInner } from './active-connections-wrapper-links-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { FormsItemDto } from './forms-item-dto';

/**
 * 
 * @export
 * @interface FormsItemArrayWrapper
 */
export interface FormsItemArrayWrapper {
    /**
     * 
     * @type {Array<FormsItemDto>}
     * @memberof FormsItemArrayWrapper
     */
    'response'?: Array<FormsItemDto>;
    /**
     * 
     * @type {number}
     * @memberof FormsItemArrayWrapper
     */
    'count'?: number;
    /**
     * 
     * @type {Array<ActiveConnectionsWrapperLinksInner>}
     * @memberof FormsItemArrayWrapper
     */
    'links'?: Array<ActiveConnectionsWrapperLinksInner>;
    /**
     * 
     * @type {number}
     * @memberof FormsItemArrayWrapper
     */
    'status'?: number;
    /**
     * 
     * @type {number}
     * @memberof FormsItemArrayWrapper
     */
    'statusCode'?: number;
}

