/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The request parameters for getting reference data.
 * @export
 * @interface GetReferenceDataDtoInteger
 */
export interface GetReferenceDataDtoInteger {
    /**
     * The unique document identifier used by the service to get a link to the file.
     * @type {string}
     * @memberof GetReferenceDataDtoInteger
     */
    'fileKey': string | null;
    /**
     * The unique system identifier.
     * @type {string}
     * @memberof GetReferenceDataDtoInteger
     */
    'instanceId'?: string | null;
    /**
     * The source file ID.
     * @type {number}
     * @memberof GetReferenceDataDtoInteger
     */
    'sourceFileId'?: number;
    /**
     * The file name or relative path for the formula editor.
     * @type {string}
     * @memberof GetReferenceDataDtoInteger
     */
    'path'?: string | null;
    /**
     * The file link.
     * @type {string}
     * @memberof GetReferenceDataDtoInteger
     */
    'link'?: string | null;
}

