/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The group summary parameters.
 * @export
 * @interface GroupSummaryDto
 */
export interface GroupSummaryDto {
    /**
     * The group ID.
     * @type {string}
     * @memberof GroupSummaryDto
     */
    'id'?: string;
    /**
     * The group name.
     * @type {string}
     * @memberof GroupSummaryDto
     */
    'name'?: string | null;
    /**
     * The group manager.
     * @type {string}
     * @memberof GroupSummaryDto
     */
    'manager'?: string | null;
}

