/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AceShortWrapper } from './ace-short-wrapper';
// May contain unused imports in some cases
// @ts-ignore
import type { EditorType } from './editor-type';

/**
 * The information config parameters.
 * @export
 * @interface InfoConfigDto
 */
export interface InfoConfigDto {
    /**
     * Specifies if the file is favorite or not.
     * @type {boolean}
     * @memberof InfoConfigDto
     */
    'favorite'?: boolean | null;
    /**
     * The folder of the file.
     * @type {string}
     * @memberof InfoConfigDto
     */
    'folder'?: string | null;
    /**
     * The file owner.
     * @type {string}
     * @memberof InfoConfigDto
     */
    'owner'?: string | null;
    /**
     * The sharing settings of the file.
     * @type {Array<AceShortWrapper>}
     * @memberof InfoConfigDto
     */
    'sharingSettings'?: Array<AceShortWrapper> | null;
    /**
     * 
     * @type {EditorType}
     * @memberof InfoConfigDto
     */
    'type'?: EditorType;
    /**
     * The uploaded file.
     * @type {string}
     * @memberof InfoConfigDto
     */
    'uploaded'?: string | null;
}



