/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ActiveConnectionsWrapperLinksInner } from './active-connections-wrapper-links-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { IsDefaultWhiteLabelLogosDto } from './is-default-white-label-logos-dto';

/**
 * 
 * @export
 * @interface IsDefaultWhiteLabelLogosWrapper
 */
export interface IsDefaultWhiteLabelLogosWrapper {
    /**
     * 
     * @type {IsDefaultWhiteLabelLogosDto}
     * @memberof IsDefaultWhiteLabelLogosWrapper
     */
    'response'?: IsDefaultWhiteLabelLogosDto;
    /**
     * 
     * @type {number}
     * @memberof IsDefaultWhiteLabelLogosWrapper
     */
    'count'?: number;
    /**
     * 
     * @type {Array<ActiveConnectionsWrapperLinksInner>}
     * @memberof IsDefaultWhiteLabelLogosWrapper
     */
    'links'?: Array<ActiveConnectionsWrapperLinksInner>;
    /**
     * 
     * @type {number}
     * @memberof IsDefaultWhiteLabelLogosWrapper
     */
    'status'?: number;
    /**
     * 
     * @type {number}
     * @memberof IsDefaultWhiteLabelLogosWrapper
     */
    'statusCode'?: number;
}

