/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ItemKeyValuePairObjectObject
 */
export interface ItemKeyValuePairObjectObject {
    /**
     * 
     * @type {any}
     * @memberof ItemKeyValuePairObjectObject
     */
    'key'?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ItemKeyValuePairObjectObject
     */
    'value'?: any | null;
}

