/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Defines the types of the sharing links.
 * @export
 * @enum {number}
 */

export const LinkType = {
    /**
    * Invitation
    */
    Invitation: 0,
    /**
    * External
    */
    External: 1
} as const;

export type LinkType = typeof LinkType[keyof typeof LinkType];



