/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The request parameters for linking accounts.
 * @export
 * @interface LinkAccountRequestDto
 */
export interface LinkAccountRequestDto {
    /**
     * The third-party profile in the serialized format.
     * @type {string}
     * @memberof LinkAccountRequestDto
     */
    'serializedProfile'?: string | null;
}

