/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiDateTime } from './api-date-time';
// May contain unused imports in some cases
// @ts-ignore
import type { RoomNewItemsDto } from './room-new-items-dto';

/**
 * The new item parameters.
 * @export
 * @interface NewItemsDtoRoomNewItemsDto
 */
export interface NewItemsDtoRoomNewItemsDto {
    /**
     * 
     * @type {ApiDateTime}
     * @memberof NewItemsDtoRoomNewItemsDto
     */
    'date'?: ApiDateTime;
    /**
     * The list of items.
     * @type {Array<RoomNewItemsDto>}
     * @memberof NewItemsDtoRoomNewItemsDto
     */
    'items'?: Array<RoomNewItemsDto> | null;
}

