/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Oauth2TokenPost200Response
 */
export interface Oauth2TokenPost200Response {
    /**
     * 
     * @type {string}
     * @memberof Oauth2TokenPost200Response
     */
    'access_token'?: string;
    /**
     * 
     * @type {string}
     * @memberof Oauth2TokenPost200Response
     */
    'token_type'?: string;
    /**
     * 
     * @type {number}
     * @memberof Oauth2TokenPost200Response
     */
    'expires_in'?: number;
    /**
     * 
     * @type {string}
     * @memberof Oauth2TokenPost200Response
     */
    'refresh_token'?: string;
}

