/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The request parameters for configuring the password complexity requirements.
 * @export
 * @interface PasswordSettingsRequestsDto
 */
export interface PasswordSettingsRequestsDto {
    /**
     * The minimum number of characters required for valid passwords.
     * @type {number}
     * @memberof PasswordSettingsRequestsDto
     */
    'minLength'?: number;
    /**
     * Specifies whether the password should contain the uppercase letters or not.
     * @type {boolean}
     * @memberof PasswordSettingsRequestsDto
     */
    'upperCase'?: boolean;
    /**
     * Specifies whether the password should contain the digits or not.
     * @type {boolean}
     * @memberof PasswordSettingsRequestsDto
     */
    'digits'?: boolean;
    /**
     * Specifies whether the password should contain the special symbols or not.
     * @type {boolean}
     * @memberof PasswordSettingsRequestsDto
     */
    'specSymbols'?: boolean;
}

