/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The request parameters for the payment URL configuration with quantity information.
 * @export
 * @interface PaymentUrlRequestsDto
 */
export interface PaymentUrlRequestsDto {
    /**
     * The URL where the user will be redirected after payment processing.
     * @type {string}
     * @memberof PaymentUrlRequestsDto
     */
    'backUrl'?: string | null;
    /**
     * The quantity of payment
     * @type {{ [key: string]: number; }}
     * @memberof PaymentUrlRequestsDto
     */
    'quantity'?: { [key: string]: number; } | null;
}

