/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PriceDto } from './price-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { TenantEntityQuotaSettings } from './tenant-entity-quota-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { TenantQuotaFeatureDto } from './tenant-quota-feature-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { TenantQuotaSettings } from './tenant-quota-settings';

/**
 * The quota information.
 * @export
 * @interface QuotaDto
 */
export interface QuotaDto {
    /**
     * The quota ID.
     * @type {number}
     * @memberof QuotaDto
     */
    'id'?: number;
    /**
     * The quota title.
     * @type {string}
     * @memberof QuotaDto
     */
    'title'?: string | null;
    /**
     * 
     * @type {PriceDto}
     * @memberof QuotaDto
     */
    'price'?: PriceDto;
    /**
     * Specifies if the quota is nonprofit or not.
     * @type {boolean}
     * @memberof QuotaDto
     */
    'nonProfit'?: boolean;
    /**
     * Specifies if the quota is free or not.
     * @type {boolean}
     * @memberof QuotaDto
     */
    'free'?: boolean;
    /**
     * Specifies if the quota is trial or not.
     * @type {boolean}
     * @memberof QuotaDto
     */
    'trial'?: boolean;
    /**
     * The list of tenant quota features.
     * @type {Array<TenantQuotaFeatureDto>}
     * @memberof QuotaDto
     */
    'features'?: Array<TenantQuotaFeatureDto> | null;
    /**
     * 
     * @type {TenantEntityQuotaSettings}
     * @memberof QuotaDto
     */
    'usersQuota'?: TenantEntityQuotaSettings;
    /**
     * 
     * @type {TenantEntityQuotaSettings}
     * @memberof QuotaDto
     */
    'roomsQuota'?: TenantEntityQuotaSettings;
    /**
     * 
     * @type {TenantQuotaSettings}
     * @memberof QuotaDto
     */
    'tenantCustomQuota'?: TenantQuotaSettings;
}

