/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Operation } from './operation';

/**
 * 
 * @export
 * @interface Report
 */
export interface Report {
    /**
     * 
     * @type {Array<Operation>}
     * @memberof Report
     */
    'collection'?: Array<Operation> | null;
    /**
     * 
     * @type {number}
     * @memberof Report
     */
    'offset'?: number;
    /**
     * 
     * @type {number}
     * @memberof Report
     */
    'limit'?: number;
    /**
     * 
     * @type {number}
     * @memberof Report
     */
    'totalQuantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof Report
     */
    'totalPage'?: number;
    /**
     * 
     * @type {number}
     * @memberof Report
     */
    'currentPage'?: number;
}

