/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ActiveConnectionsWrapperLinksInner } from './active-connections-wrapper-links-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { RoomSecurityDto } from './room-security-dto';

/**
 * 
 * @export
 * @interface RoomSecurityWrapper
 */
export interface RoomSecurityWrapper {
    /**
     * 
     * @type {RoomSecurityDto}
     * @memberof RoomSecurityWrapper
     */
    'response'?: RoomSecurityDto;
    /**
     * 
     * @type {number}
     * @memberof RoomSecurityWrapper
     */
    'count'?: number;
    /**
     * 
     * @type {Array<ActiveConnectionsWrapperLinksInner>}
     * @memberof RoomSecurityWrapper
     */
    'links'?: Array<ActiveConnectionsWrapperLinksInner>;
    /**
     * 
     * @type {number}
     * @memberof RoomSecurityWrapper
     */
    'status'?: number;
    /**
     * 
     * @type {number}
     * @memberof RoomSecurityWrapper
     */
    'statusCode'?: number;
}

