/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiDateTime } from './api-date-time';
// May contain unused imports in some cases
// @ts-ignore
import type { FileShare } from './file-share';
// May contain unused imports in some cases
// @ts-ignore
import type { LinkType } from './link-type';

/**
 * The room link parameters.
 * @export
 * @interface RoomLinkRequest
 */
export interface RoomLinkRequest {
    /**
     * The room link ID.
     * @type {string}
     * @memberof RoomLinkRequest
     */
    'linkId'?: string;
    /**
     * 
     * @type {FileShare}
     * @memberof RoomLinkRequest
     */
    'access'?: FileShare;
    /**
     * 
     * @type {ApiDateTime}
     * @memberof RoomLinkRequest
     */
    'expirationDate'?: ApiDateTime;
    /**
     * The link name.
     * @type {string}
     * @memberof RoomLinkRequest
     */
    'title'?: string | null;
    /**
     * 
     * @type {LinkType}
     * @memberof RoomLinkRequest
     */
    'linkType'?: LinkType;
    /**
     * The link password.
     * @type {string}
     * @memberof RoomLinkRequest
     */
    'password'?: string | null;
    /**
     * Specifies if downloading the file from the link is disabled or not.
     * @type {boolean}
     * @memberof RoomLinkRequest
     */
    'denyDownload'?: boolean;
}



