/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The request parameters for configuring notification settings for the chat or collaboration rooms.
 * @export
 * @interface RoomsNotificationsSettingsRequestDto
 */
export interface RoomsNotificationsSettingsRequestDto {
    /**
     * The target room identifier.
     * @type {any}
     * @memberof RoomsNotificationsSettingsRequestDto
     */
    'roomsId'?: any | null;
    /**
     * Specifies whether the notifications will be delivered to the specified room or not.
     * @type {boolean}
     * @memberof RoomsNotificationsSettingsRequestDto
     */
    'mute'?: boolean;
}

