/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The room template status.
 * @export
 * @interface RoomTemplateStatusDto
 */
export interface RoomTemplateStatusDto {
    /**
     * The room template ID.
     * @type {number}
     * @memberof RoomTemplateStatusDto
     */
    'templateId'?: number;
    /**
     * The progress of the room template creation process.
     * @type {number}
     * @memberof RoomTemplateStatusDto
     */
    'progress'?: number;
    /**
     * The error message that is sent when the room template is not created successfully.
     * @type {string}
     * @memberof RoomTemplateStatusDto
     */
    'error'?: string | null;
    /**
     * Specifies whether the process of creating the room template is completed.
     * @type {boolean}
     * @memberof RoomTemplateStatusDto
     */
    'isCompleted'?: boolean;
}

