/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RoomInvitation } from './room-invitation';

/**
 * The request parameters for inviting users to the room.
 * @export
 * @interface RoomInvitationRequest
 */
export interface RoomInvitationRequest {
    /**
     * The collection of invitation parameters.
     * @type {Array<RoomInvitation>}
     * @memberof RoomInvitationRequest
     */
    'invitations'?: Array<RoomInvitation> | null;
    /**
     * Specifies whether to notify users about the shared room or not.
     * @type {boolean}
     * @memberof RoomInvitationRequest
     */
    'notify'?: boolean;
    /**
     * The message to send when notifying about the shared room.
     * @type {string}
     * @memberof RoomInvitationRequest
     */
    'message'?: string | null;
    /**
     * The language of the room invitation.
     * @type {string}
     * @memberof RoomInvitationRequest
     */
    'culture'?: string | null;
    /**
     * Specifies whether to forcibly delete a user with form roles from the room.
     * @type {boolean}
     * @memberof RoomInvitationRequest
     */
    'force'?: boolean;
}

