/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RoomDataLifetimePeriod } from './room-data-lifetime-period';

/**
 * The room data lifetime information.
 * @export
 * @interface RoomDataLifetimeDto
 */
export interface RoomDataLifetimeDto {
    /**
     * Specifies whether to permanently delete the room data or not.
     * @type {boolean}
     * @memberof RoomDataLifetimeDto
     */
    'deletePermanently'?: boolean;
    /**
     * 
     * @type {RoomDataLifetimePeriod}
     * @memberof RoomDataLifetimeDto
     */
    'period'?: RoomDataLifetimePeriod;
    /**
     * Specifies the time period value of the room data lifetime.
     * @type {number}
     * @memberof RoomDataLifetimeDto
     */
    'value'?: number | null;
    /**
     * Specifies whether the room data lifetime setting is enabled or not.
     * @type {boolean}
     * @memberof RoomDataLifetimeDto
     */
    'enabled'?: boolean | null;
}



