/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ScopeResponse
 */
export interface ScopeResponse {
    /**
     * 
     * @type {string}
     * @memberof ScopeResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ScopeResponse
     */
    'group'?: string;
    /**
     * 
     * @type {string}
     * @memberof ScopeResponse
     */
    'type'?: string;
}

