/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * [0 - User or group, 1 - Invitation link, 2 - External link, 4 - Additional external link, 8 - Primary external link, 16 - User, 32 - Group]
 * @export
 * @enum {number}
 */

export const ShareFilterType = {
    /**
    * User or group
    */
    UserOrGroup: 0,
    /**
    * Invitation link
    */
    InvitationLink: 1,
    /**
    * External link
    */
    ExternalLink: 2,
    /**
    * Additional external link
    */
    AdditionalExternalLink: 4,
    /**
    * Primary external link
    */
    PrimaryExternalLink: 8,
    /**
    * User
    */
    User: 16,
    /**
    * Group
    */
    Group: 32
} as const;

export type ShareFilterType = typeof ShareFilterType[keyof typeof ShareFilterType];



