/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * [0 - Date and time, 1 - AZ, 2 - Size, 3 - Author, 4 - Type, 5 - New, 6 - Date and time creation, 7 - Room type, 8 - Tags, 9 - Room, 10 - Custom order, 11 - Last opened, 12 - Used space]
 * @export
 * @enum {number}
 */

export const SortedByType = {
    /**
    * Date and time
    */
    DateAndTime: 0,
    /**
    * AZ
    */
    AZ: 1,
    /**
    * Size
    */
    Size: 2,
    /**
    * Author
    */
    Author: 3,
    /**
    * Type
    */
    Type: 4,
    /**
    * New
    */
    New: 5,
    /**
    * Date and time creation
    */
    DateAndTimeCreation: 6,
    /**
    * Room type
    */
    RoomType: 7,
    /**
    * Tags
    */
    Tags: 8,
    /**
    * Room
    */
    Room: 9,
    /**
    * Custom order
    */
    CustomOrder: 10,
    /**
    * Last opened
    */
    LastOpened: 11,
    /**
    * Used space
    */
    UsedSpace: 12
} as const;

export type SortedByType = typeof SortedByType[keyof typeof SortedByType];



