/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The parameters of the button that starts filling out the form.
 * @export
 * @interface StartFillingForm
 */
export interface StartFillingForm {
    /**
     * The caption of the button that starts filling out the form.
     * @type {string}
     * @memberof StartFillingForm
     */
    'text'?: string | null;
}

