/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The request parameters for starting the reassignment process.
 * @export
 * @interface StartReassignRequestDto
 */
export interface StartReassignRequestDto {
    /**
     * The user ID whose data will be reassigned to another user.
     * @type {string}
     * @memberof StartReassignRequestDto
     */
    'fromUserId': string;
    /**
     * The user ID to whom all the data will be reassigned.
     * @type {string}
     * @memberof StartReassignRequestDto
     */
    'toUserId': string;
    /**
     * Specifies whether to delete a profile when the data reassignment will be finished or not.
     * @type {boolean}
     * @memberof StartReassignRequestDto
     */
    'deleteProfile'?: boolean;
}

