/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The start filling mode.
 * @export
 * @enum {number}
 */

export const StartFillingMode = {
    /**
    * None
    */
    None: 0,
    /**
    * Share to fill out
    */
    ShareToFillOut: 1,
    /**
    * Start filling
    */
    StartFilling: 2
} as const;

export type StartFillingMode = typeof StartFillingMode[keyof typeof StartFillingMode];



