/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {number}
 */

export const StorageFilter = {
    /**
    * None
    */
    None: 0,
    /**
    * Internal
    */
    Internal: 1,
    /**
    * ThirdParty
    */
    ThirdParty: 2
} as const;

export type StorageFilter = typeof StorageFilter[keyof typeof StorageFilter];



