/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubAccount
 */
export interface SubAccount {
    /**
     * 
     * @type {string}
     * @memberof SubAccount
     */
    'currency'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SubAccount
     */
    'amount'?: number;
}

