/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The tariff state.
 * @export
 * @enum {number}
 */

export const TariffState = {
    /**
    * Trial
    */
    Trial: 0,
    /**
    * Paid
    */
    Paid: 1,
    /**
    * Delay
    */
    Delay: 2,
    /**
    * Not paid
    */
    NotPaid: 3
} as const;

export type TariffState = typeof TariffState[keyof typeof TariffState];



