/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DistributedTaskStatus } from './distributed-task-status';

/**
 * The task progress response parameters.
 * @export
 * @interface TaskProgressResponseDto
 */
export interface TaskProgressResponseDto {
    /**
     * The task progress ID.
     * @type {string}
     * @memberof TaskProgressResponseDto
     */
    'id'?: string | null;
    /**
     * The task progress error message.
     * @type {string}
     * @memberof TaskProgressResponseDto
     */
    'error'?: string | null;
    /**
     * The percentage of the task progress.
     * @type {number}
     * @memberof TaskProgressResponseDto
     */
    'percentage'?: number;
    /**
     * Specifies if the task peogress is completed or not.
     * @type {boolean}
     * @memberof TaskProgressResponseDto
     */
    'isCompleted'?: boolean;
    /**
     * 
     * @type {DistributedTaskStatus}
     * @memberof TaskProgressResponseDto
     */
    'status'?: DistributedTaskStatus;
}



