/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The tenant quota settings.
 * @export
 * @interface TenantQuotaSettings
 */
export interface TenantQuotaSettings {
    /**
     * Specifies if the tenant quota is enabled or not.
     * @type {boolean}
     * @memberof TenantQuotaSettings
     */
    'enableQuota'?: boolean;
    /**
     * The tenant quota.
     * @type {number}
     * @memberof TenantQuotaSettings
     */
    'quota'?: number;
    /**
     * The date of the last tenant quota recalculation.
     * @type {string}
     * @memberof TenantQuotaSettings
     */
    'lastRecalculateDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TenantQuotaSettings
     */
    'lastModified'?: string;
}

