/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TenantWalletSettings
 */
export interface TenantWalletSettings {
    /**
     * Enabled
     * @type {boolean}
     * @memberof TenantWalletSettings
     */
    'enabled'?: boolean;
    /**
     * Minimun balance
     * @type {number}
     * @memberof TenantWalletSettings
     */
    'minBalance'?: number;
    /**
     * Up to balance
     * @type {number}
     * @memberof TenantWalletSettings
     */
    'upToBalance'?: number;
    /**
     * Currency
     * @type {string}
     * @memberof TenantWalletSettings
     */
    'currency'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TenantWalletSettings
     */
    'lastModified'?: string;
}

