/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The tenant status.
 * @export
 * @enum {number}
 */

export const TenantStatus = {
    /**
    * Active
    */
    Active: 0,
    /**
    * Suspended
    */
    Suspended: 1,
    /**
    * Remove pending
    */
    RemovePending: 2,
    /**
    * Transfering
    */
    Transfering: 3,
    /**
    * Restoring
    */
    Restoring: 4,
    /**
    * Migrating
    */
    Migrating: 5,
    /**
    * Encryption
    */
    Encryption: 6
} as const;

export type TenantStatus = typeof TenantStatus[keyof typeof TenantStatus];



