/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The user quota settings.
 * @export
 * @interface TenantUserQuotaSettings
 */
export interface TenantUserQuotaSettings {
    /**
     * Specifies if the quota is enabled for the tenant entity or not.
     * @type {boolean}
     * @memberof TenantUserQuotaSettings
     */
    'enableQuota'?: boolean;
    /**
     * The default quota of the tenant entity.
     * @type {number}
     * @memberof TenantUserQuotaSettings
     */
    'defaultQuota'?: number;
    /**
     * The date of the last quota recalculation.
     * @type {string}
     * @memberof TenantUserQuotaSettings
     */
    'lastRecalculateDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TenantUserQuotaSettings
     */
    'lastModified'?: string;
}

