/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The request parameters for managing the Developer Tools access settings for the current tenant.
 * @export
 * @interface TenantDevToolsAccessSettingsDto
 */
export interface TenantDevToolsAccessSettingsDto {
    /**
     * Determines if users have restricted access to the Developer Tools.
     * @type {boolean}
     * @memberof TenantDevToolsAccessSettingsDto
     */
    'limitedAccessForUsers'?: boolean;
}

