/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The tenant entity quota settings.
 * @export
 * @interface TenantEntityQuotaSettings
 */
export interface TenantEntityQuotaSettings {
    /**
     * Specifies if the quota is enabled for the tenant entity or not.
     * @type {boolean}
     * @memberof TenantEntityQuotaSettings
     */
    'enableQuota'?: boolean;
    /**
     * The default quota of the tenant entity.
     * @type {number}
     * @memberof TenantEntityQuotaSettings
     */
    'defaultQuota'?: number;
    /**
     * The date of the last quota recalculation.
     * @type {string}
     * @memberof TenantEntityQuotaSettings
     */
    'lastRecalculateDate'?: string | null;
}

