/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ActiveConnectionsWrapperLinksInner } from './active-connections-wrapper-links-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ThirdPartyParams } from './third-party-params';

/**
 * 
 * @export
 * @interface ThirdPartyParamsArrayWrapper
 */
export interface ThirdPartyParamsArrayWrapper {
    /**
     * 
     * @type {Array<ThirdPartyParams>}
     * @memberof ThirdPartyParamsArrayWrapper
     */
    'response'?: Array<ThirdPartyParams>;
    /**
     * 
     * @type {number}
     * @memberof ThirdPartyParamsArrayWrapper
     */
    'count'?: number;
    /**
     * 
     * @type {Array<ActiveConnectionsWrapperLinksInner>}
     * @memberof ThirdPartyParamsArrayWrapper
     */
    'links'?: Array<ActiveConnectionsWrapperLinksInner>;
    /**
     * 
     * @type {number}
     * @memberof ThirdPartyParamsArrayWrapper
     */
    'status'?: number;
    /**
     * 
     * @type {number}
     * @memberof ThirdPartyParamsArrayWrapper
     */
    'statusCode'?: number;
}

