/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthData } from './auth-data';

/**
 * The third-party account parameters.
 * @export
 * @interface ThirdPartyParams
 */
export interface ThirdPartyParams {
    /**
     * 
     * @type {AuthData}
     * @memberof ThirdPartyParams
     */
    'auth_data'?: AuthData;
    /**
     * Specifies if this is a corporate account or not.
     * @type {boolean}
     * @memberof ThirdPartyParams
     */
    'corporate'?: boolean;
    /**
     * Specifies if this is a room storage or not.
     * @type {boolean}
     * @memberof ThirdPartyParams
     */
    'roomsStorage'?: boolean;
    /**
     * The customer title.
     * @type {string}
     * @memberof ThirdPartyParams
     */
    'customer_title'?: string | null;
    /**
     * The provider ID.
     * @type {number}
     * @memberof ThirdPartyParams
     */
    'provider_id'?: number | null;
    /**
     * The provider key.
     * @type {string}
     * @memberof ThirdPartyParams
     */
    'provider_key'?: string | null;
}

