/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The thumbnails data parameters.
 * @export
 * @interface ThumbnailsDataDto
 */
export interface ThumbnailsDataDto {
    /**
     * The thumbnail original photo.
     * @type {string}
     * @memberof ThumbnailsDataDto
     */
    'original'?: string | null;
    /**
     * The thumbnail retina.
     * @type {string}
     * @memberof ThumbnailsDataDto
     */
    'retina'?: string | null;
    /**
     * The thumbnail maximum size photo.
     * @type {string}
     * @memberof ThumbnailsDataDto
     */
    'max'?: string | null;
    /**
     * The thumbnail big size photo.
     * @type {string}
     * @memberof ThumbnailsDataDto
     */
    'big'?: string | null;
    /**
     * The thumbnail medium size photo.
     * @type {string}
     * @memberof ThumbnailsDataDto
     */
    'medium'?: string | null;
    /**
     * The thumbnail small size photo.
     * @type {string}
     * @memberof ThumbnailsDataDto
     */
    'small'?: string | null;
}

