/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The request parameters for enabling or disabling administrator messaging system.
 * @export
 * @interface TurnOnAdminMessageSettingsRequestDto
 */
export interface TurnOnAdminMessageSettingsRequestDto {
    /**
     * The global switch for the administrator messaging functionality.
     * @type {boolean}
     * @memberof TurnOnAdminMessageSettingsRequestDto
     */
    'turnOn'?: boolean;
}

