/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The parameters for updating a file.
 * @export
 * @interface UpdateFile
 */
export interface UpdateFile {
    /**
     * The file title to update.
     * @type {string}
     * @memberof UpdateFile
     */
    'title'?: string | null;
    /**
     * The number of the latest file version.
     * @type {number}
     * @memberof UpdateFile
     */
    'lastVersion'?: number;
}

