/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The user invitation parameters.
 * @export
 * @interface UserInvitation
 */
export interface UserInvitation {
    /**
     * The list of user IDs.
     * @type {Array<string>}
     * @memberof UserInvitation
     */
    'usersIds'?: Array<string> | null;
    /**
     * Specifies whether to resend all user invitations or not.
     * @type {boolean}
     * @memberof UserInvitation
     */
    'resendAll'?: boolean;
}

