/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The watermark additions.
 * @export
 * @enum {number}
 */

export const WatermarkAdditions = {
    /**
    * User name
    */
    UserName: 1,
    /**
    * User email
    */
    UserEmail: 2,
    /**
    * User ip adress
    */
    UserIpAdress: 4,
    /**
    * Current date
    */
    CurrentDate: 8,
    /**
    * Room name
    */
    RoomName: 16
} as const;

export type WatermarkAdditions = typeof WatermarkAdditions[keyof typeof WatermarkAdditions];



