/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EmployeeDto } from './employee-dto';

/**
 * The web plugin information.
 * @export
 * @interface WebPluginDto
 */
export interface WebPluginDto {
    /**
     * The web plugin name.
     * @type {string}
     * @memberof WebPluginDto
     */
    'name'?: string | null;
    /**
     * The web plugin version.
     * @type {string}
     * @memberof WebPluginDto
     */
    'version'?: string | null;
    /**
     * The web plugin description.
     * @type {string}
     * @memberof WebPluginDto
     */
    'description'?: string | null;
    /**
     * The web plugin license.
     * @type {string}
     * @memberof WebPluginDto
     */
    'license'?: string | null;
    /**
     * The web plugin author.
     * @type {string}
     * @memberof WebPluginDto
     */
    'author'?: string | null;
    /**
     * The web plugin home page URL.
     * @type {string}
     * @memberof WebPluginDto
     */
    'homePage'?: string | null;
    /**
     * The name by which the web plugin is registered in the window object.
     * @type {string}
     * @memberof WebPluginDto
     */
    'pluginName'?: string | null;
    /**
     * The web plugin scopes.
     * @type {string}
     * @memberof WebPluginDto
     */
    'scopes'?: string | null;
    /**
     * The web plugin image.
     * @type {string}
     * @memberof WebPluginDto
     */
    'image'?: string | null;
    /**
     * 
     * @type {EmployeeDto}
     * @memberof WebPluginDto
     */
    'createBy'?: EmployeeDto;
    /**
     * The date and time when the web plugin was created.
     * @type {string}
     * @memberof WebPluginDto
     */
    'createOn'?: string;
    /**
     * Specifies if the web plugin is enabled or not.
     * @type {boolean}
     * @memberof WebPluginDto
     */
    'enabled'?: boolean;
    /**
     * Specifies if the web plugin is system or not.
     * @type {boolean}
     * @memberof WebPluginDto
     */
    'system'?: boolean;
    /**
     * The web plugin URL.
     * @type {string}
     * @memberof WebPluginDto
     */
    'url'?: string | null;
    /**
     * The web plugin settings.
     * @type {string}
     * @memberof WebPluginDto
     */
    'settings'?: string | null;
}

