/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WebhookTrigger } from './webhook-trigger';

/**
 * The request parameters for creating or updating the webhook configuration.
 * @export
 * @interface WebhooksConfigRequestsDto
 */
export interface WebhooksConfigRequestsDto {
    /**
     * The webhook configuration ID.
     * @type {number}
     * @memberof WebhooksConfigRequestsDto
     */
    'id'?: number;
    /**
     * The human-readable name of the webhook configuration.
     * @type {string}
     * @memberof WebhooksConfigRequestsDto
     */
    'name': string;
    /**
     * The destination URL where the webhook events will be sent.
     * @type {string}
     * @memberof WebhooksConfigRequestsDto
     */
    'uri': string;
    /**
     * The webhook secret key used to sign the webhook payloads for the security verification.
     * @type {string}
     * @memberof WebhooksConfigRequestsDto
     */
    'secretKey'?: string | null;
    /**
     * Specifies whether the webhook configuration is active or not.
     * @type {boolean}
     * @memberof WebhooksConfigRequestsDto
     */
    'enabled'?: boolean;
    /**
     * Specifies whether the SSL certificate verification is required or not.
     * @type {boolean}
     * @memberof WebhooksConfigRequestsDto
     */
    'ssl'?: boolean;
    /**
     * 
     * @type {WebhookTrigger}
     * @memberof WebhooksConfigRequestsDto
     */
    'triggers'?: WebhookTrigger;
    /**
     * Target ID
     * @type {string}
     * @memberof WebhooksConfigRequestsDto
     */
    'targetId'?: string | null;
}



