/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WebhookTrigger } from './webhook-trigger';

/**
 * The webhook log parameters.
 * @export
 * @interface WebhooksLogDto
 */
export interface WebhooksLogDto {
    /**
     * The webhook log ID.
     * @type {number}
     * @memberof WebhooksLogDto
     */
    'id'?: number;
    /**
     * The webhook configuration name.
     * @type {string}
     * @memberof WebhooksLogDto
     */
    'configName'?: string | null;
    /**
     * 
     * @type {WebhookTrigger}
     * @memberof WebhooksLogDto
     */
    'trigger'?: WebhookTrigger;
    /**
     * The webhook creation time.
     * @type {string}
     * @memberof WebhooksLogDto
     */
    'creationTime'?: string;
    /**
     * The webhook method.
     * @type {string}
     * @memberof WebhooksLogDto
     */
    'method'?: string | null;
    /**
     * The webhook route.
     * @type {string}
     * @memberof WebhooksLogDto
     */
    'route'?: string | null;
    /**
     * The webhook request headers.
     * @type {string}
     * @memberof WebhooksLogDto
     */
    'requestHeaders'?: string | null;
    /**
     * The webhook request payload.
     * @type {string}
     * @memberof WebhooksLogDto
     */
    'requestPayload'?: string | null;
    /**
     * The webhook response headers.
     * @type {string}
     * @memberof WebhooksLogDto
     */
    'responseHeaders'?: string | null;
    /**
     * The webhook response payload.
     * @type {string}
     * @memberof WebhooksLogDto
     */
    'responsePayload'?: string | null;
    /**
     * The webhook status.
     * @type {number}
     * @memberof WebhooksLogDto
     */
    'status'?: number;
    /**
     * The webhook delivery time.
     * @type {string}
     * @memberof WebhooksLogDto
     */
    'delivery'?: string | null;
}



