/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IMagickGeometry } from './imagick-geometry';
// May contain unused imports in some cases
// @ts-ignore
import type { WhiteLabelItemPathDto } from './white-label-item-path-dto';

/**
 * The white label item parameters.
 * @export
 * @interface WhiteLabelItemDto
 */
export interface WhiteLabelItemDto {
    /**
     * The white label file name.
     * @type {string}
     * @memberof WhiteLabelItemDto
     */
    'name'?: string | null;
    /**
     * 
     * @type {IMagickGeometry}
     * @memberof WhiteLabelItemDto
     */
    'size'?: IMagickGeometry;
    /**
     * 
     * @type {WhiteLabelItemPathDto}
     * @memberof WhiteLabelItemDto
     */
    'path'?: WhiteLabelItemPathDto;
}

