/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The white label item path parameters.
 * @export
 * @interface WhiteLabelItemPathDto
 */
export interface WhiteLabelItemPathDto {
    /**
     * The path to the light theme logo.
     * @type {string}
     * @memberof WhiteLabelItemPathDto
     */
    'light'?: string | null;
    /**
     * The path to the dark theme logo.
     * @type {string}
     * @memberof WhiteLabelItemPathDto
     */
    'dark'?: string | null;
}

