/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@onlyoffice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The Wizard settings.
 * @export
 * @interface WizardSettings
 */
export interface WizardSettings {
    /**
     * Specifies if the Wizard settings are completed or not
     * @type {boolean}
     * @memberof WizardSettings
     */
    'completed'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WizardSettings
     */
    'lastModified'?: string;
}

